### PR TITLE
References: introduce channels.

### PR DESCRIPTION
**Pull request by frankban**
The Reference object know handles optional channels.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-bundlelib/57/
Test PASSed.

**Comment by urosj** [comment]
:+1:

**Comment by fabricematrat** [comment]
:+1:

**Comment by frankban** [comment]
Thanks for the reviews!
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-bundlelib-merge

**Pull request merged**
