### PR TITLE
Reference.from_jujucharms_url: do not assume a reference is a bundle...

### PR DESCRIPTION
**Pull request by frankban**
…when not specified.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-bundlelib/63/
Test PASSed.

**Comment by fabricematrat** [comment]
:+1:  thanks !

**Comment by frankban** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-bundlelib-merge

**Pull request merged**
