### PR TITLE
Add availability-zone to constraints

### LINKED ISSUE #53: availability zone missing in _CONSTRAINTS
Via @huwshimi:

When I try and deploy a bundle with availability zones e.g.

```
machines: 
  "0": 
    series: precise
    constraints: "arch=amd64 cpu-cores=1 cpu-power=300 mem=3840 root-disk=8192 availability-zone=ap-southeast-2a"
```

I get this follow error:

```
The following errors occurred while retrieving bundle changes: invalid constraints "arch=amd64 cpu-cores=1 cpu-power=300 mem=3840 root-disk=8192 availability-zone=ap-southeast-2b" in machine "1": unknown constraint "availability-zone", invalid constraints "arch=amd64 cpu-cores=1 cpu-power=300 mem=3840 root-disk=8192 availability-zone=ap-southeast-2a" in machine "0": unknown constraint "availability-zone"
```

### PR DESCRIPTION
**Pull request by makyo**
fixes #53

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-bundlelib/89/
Test PASSed.

**Comment by frankban** [comment]
:+1: ship it

**Comment by hatched** [comment]
:+1: Thanks @makyo

**Comment by makyo** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-bundlelib-merge

**Pull request merged**
