### PR TITLE
Add packaging instructions.

### PR DESCRIPTION
**Pull request by frankban**

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-bundlelib/40/
Test PASSed.

**Comment by makyo** [comment]
:+1: nice and clear, thanks

**Comment by frankban** [comment]
Thanks for the review Madison.
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-bundlelib-merge

**Pull request merged**
