### PR TITLE
Unpin PyYaml.

### PR DESCRIPTION
**Pull request by frankban**
Fixes https://github.com/juju/juju-bundlelib/issues/55

### CODE REVIEW

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-bundlelib/97/

**Comment by battlemidget** [comment]
LGTM +1

**Comment by frankban** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-bundlelib-merge

**Pull request merged**
