### PR TITLE
Introduce expose change.

### PR DESCRIPTION
**Pull request by frankban**
Handle validating the service expose fields.
Generate proper expose changes when required.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-bundlelib/55/
Test PASSed.

**Comment by frankban** [comment]
Tests: `make check`.

QA:
save this bundle as /tmp/media.yaml:
```
services:
  mediawiki:
    charm: cs:trusty/mediawiki-3
    num_units: 1
    expose: true
  mysql:
    charm: cs:trusty/mysql-29
    num_units: 1
series: trusty
relations:
- - mediawiki:db
  - mysql:db
```
The run `devenv/bin/getchangeset /tmp/media.yaml` and ensure an expose-2 change is included in the output.

**Comment by hatched** [comment]
:+1:

**Comment by makyo** [comment]
:+1: QA :ok:

**Comment by makyo** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-bundlelib-merge

**Pull request merged**
