### PR TITLE
Do not check series if the unit is not hulk-smashed.

### PR DESCRIPTION
**Pull request by frankban**
Fixes https://github.com/juju/juju-bundlelib/issues/31

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-bundlelib/42/
Test PASSed.

**Comment by bac** [comment]
:+1:

**Comment by frankban** [comment]
:shipit:

**Comment by frankban** [comment]
Thanks for the review Brad!

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-bundlelib-merge

**Pull request merged**
