### PR TITLE
Rename the validate module to validation.

### PR DESCRIPTION
**Pull request by frankban**
Also return an error if the services dict is empty in the bundle YAML.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-bundlelib/16/
Test PASSed.

**Comment by bac** [comment]
:+1:

**Comment by frankban** [comment]
TY for the review Brad.
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://localhost:8080/job/juju-bundlelib-merge

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://localhost:8080/job/juju-bundlelib-merge

**Pull request merged**
