### PR TITLE
Make sysdeps smarter by using an included file.

### PR DESCRIPTION
**Pull request by bac**

### CODE REVIEW

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-bundlelib/29/
Test FAILed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-bundlelib/30/
Test PASSed.

**Comment by makyo** [comment]
:+1: - this should help simplify CI

**Comment by bac** [comment]
Thanks @makyo . :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://localhost:8080/job/juju-bundlelib-merge

**Pull request merged**
